#ifndef RTC_STATUS_CODE_H
#define RTC_STATUS_CODE_H

typedef enum {
    HAL_RTC_OK = 0,
    HAL_RTC_ERR_NOT_INITIALIZED,
    HAL_RTC_ERR_INVALID_PARAMETER,
    HAL_RTC_ERR_INVALID_DATA,
    HAL_RTC_ERR_TIMEOUT,
    HAL_RTC_ERR_HW_FAILURE,
    HAL_RTC_ERR_UNSUPPORTED
} hal_rtc_status_t;

#endif
